---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: aws-sync
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: aws-cli
              image: amazon/aws-cli:latest
              imagePullPolicy: IfNotPresent
              command:
                - aws
                - s3
                - sync
                - s3://juniqe-staging-shop-images
                - s3://juniqe-staging-shop-images-sync
          restartPolicy: OnFailure
  schedule: 0 6 * * 1-5